language: python
sudo: false

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=3.7.5 PYGAME_VERSION=1.9.6
      before_install:
        - brew update
        # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
        - brew install openssl readline
        # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
        # I didn't do this above because it works and I'm lazy.
        - brew outdated pyenv || brew upgrade pyenv
        # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
        # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
        - brew install pyenv-virtualenv
        - pyenv install $PYTHON
        # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
        # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
        # modify the Bash environment. ??? So, I hand-set the variables instead.
        - export PYENV_VERSION=$PYTHON
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv virtualenv py_venv
        - source py_venv/bin/activate
        # A manual check that the correct version of Python is running.
        - python --version
    - os: windows
      language: sh
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python --version
      env: PYGAME_VERSION=1.9.6
    - os: windows
      language: sh
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python --version
      env: PYGAME_VERSION=2.0.0.dev6
    - os: linux
      python: 3.5
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.5
      env: PYGAME_VERSION=2.0.0.dev6
    - os: linux
      python: 3.6
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.6
      env: PYGAME_VERSION=2.0.0.dev6
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=2.0.0.dev6
    # No Travis version of 1.9.6 on Python 3.8 yet
    - os: linux
      python: 3.8
      env: PYGAME_VERSION=2.0.0.dev6

install:
  - python -m pip install -U pip
  - python -m pip install pytest
  - python -m pip install pytest-cov
  - python -m pip install codecov
  - python -m pip install -q pygame==$PYGAME_VERSION
  - python setup.py -q install

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

script: pytest --cov-report=xml --cov=pygame_gui tests/

after_success:
    - codecov