language: python
sudo: false

matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python --version
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.5
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.5
      env: PYGAME_VERSION=2.0.0.dev6
    - os: linux
      python: 3.6
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.6
      env: PYGAME_VERSION=2.0.0.dev6
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=2.0.0.dev6
    # No Travis version of 1.9.6 on Python 3.8 yet
    - os: linux
      python: 3.8
      env: PYGAME_VERSION=2.0.0.dev6


install:
  - python -m pip install pytest
  - python -m pip install pytest-cov
  - python -m pip install codecov
  - python -m pip install -q pygame==$PYGAME_VERSION
  - python setup.py -q install

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

script: pytest --cov-report=xml --cov=pygame_gui tests/

after_success:
    - codecov